export const partidos = [
  {
      id: 1,
      equipo1: "Argentina",
      equipo2: "Canadá",
      resultado: "1 - 0",
      fase: "De grupos",
      fecha: "20/06/2024",
      estadio: "Mercedes-Benz Stadium, Atlanta",
      goleadores: ["Julián Álvarez"],
      estadisticas: {
          equipo1: {
              remates: 15,
              remates_a_puerta: 6,
              posesion: 65,
              faltas: 10,
              tarjetas_amarillas: 1,
              corners: 4,
          },
          equipo2: {
              remates: 8,
              remates_a_puerta: 3,
              posesion: 35,
              faltas: 12,
              tarjetas_amarillas: 2,
              corners: 2,
          },
      },
  },
  {
    id: 2,
    equipo1: "Chile",
    equipo2: "Argentina",
    resultado: "0 - 1",
    fase: "De grupos",
    fecha: "25/06/2024",
    estadio: "MetLife Stadium, East Rutherford",
    goleadores: ["Lautaro Martínez"],
  },
  {
    id: 3,
    equipo1: "Argentina",
    equipo2: "Perú",
    resultado: "2 - 0",
    fase: "De grupos",
    fecha: "29/06/2024",
    estadio: "Hard Rock Stadium, Miami",
    goleadores: ["Lautaro Martínez"]
  },
  {
    id: 4,
    equipo1: "Argentina",
    equipo2: "Ecuador",
    resultado: "1 - 1",
    fase: "Cuartos de final",
    fecha: "04/07/2024",
    estadio: "NRG Stadium, Houston",
    goleadores: ["Lisandro Martínez"],
    penales: [
      { jugador: "Messi", resultado: "Fallo (travesaño)" },
      { jugador: "Álvarez", resultado: "Acierto" },
      { jugador: "Mac Allister", resultado: "Acierto" },
      { jugador: "Montiel", resultado: "Acierto" },
      { jugador: "Otamendi", resultado: "Acierto" },
      { jugador: "Mena", resultado: "Fallo (atajado)" },
      { jugador: "Minda", resultado: "Fallo (atajado)" },
      { jugador: "Yeboah", resultado: "Acierto" },
      { jugador: "J. Caicedo", resultado: "Acierto" }
    ]
  },
  {
    id: 5,
    equipo1: "Argentina",
    equipo2: "Canadá",
    resultado: "2 - 0",
    fase: "Semifinales",
    fecha: "09/07/2024",
    estadio: "MetLife Stadium, East Rutherford",
    goleadores: ["Julián Álvarez", "Lionel Messi"]
  },
  {
    id: 6,
    equipo1: "Argentina",
    equipo2: "Colombia",
    resultado: "1 - 0",
    fase: "Final",
    fecha: "14/07/2024",
    estadio: "Hard Rock Stadium, Miami",
    goleadores: ["Lautaro Martínez"]
  },
];
